fix: update rust crate avr-device to 0.9 (#44)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [avr-device](https://redirect.github.com/Rahix/avr-device) |
workspace.dependencies | minor | `0.8` → `0.9` |
| [avr-device](https://redirect.github.com/Rahix/avr-device) |
dependencies | minor | `0.8` → `0.9` |

---

### Release Notes

<details>
<summary>Rahix/avr-device (avr-device)</summary>

###
[`v0.9.0`](https://redirect.github.com/Rahix/avr-device/blob/HEAD/CHANGELOG.md#090---2026-08-04)

[Compare
Source](https://redirect.github.com/Rahix/avr-device/compare/v0.8.1...v0.9.0)

##### Added

- Support for `ATtiny10` ([#&#8203;252]).
- Support for `AVR128DB32` ([#&#8203;259]).

##### Fixed

- `ATtiny412`: Fixed `TCA0` missing and a bunch of incorrect register
fields ([#&#8203;260]).
- Fixed compilation with the Bazel build system ([#&#8203;251]). There
was a symlink
check in our build script which interferes with Bazel's source
organization.
- Fixed cargo dependency resolution errors like
  ```text
  error: failed to select a version for `syn`.
  ```
  caused by `avr-device` having had a pinned version of `syn` in its
  build-dependencies. Same fix for `yaml-rust2` ([#&#8203;267]).

[#&#8203;251]: https://redirect.github.com/Rahix/avr-device/pull/251

[#&#8203;252]: https://redirect.github.com/Rahix/avr-device/pull/252

[#&#8203;259]: https://redirect.github.com/Rahix/avr-device/pull/259

[#&#8203;260]: https://redirect.github.com/Rahix/avr-device/pull/260

[#&#8203;267]: https://redirect.github.com/Rahix/avr-device/pull/267

</details>

---

### Configuration

📅 **Schedule**: (UTC)

- Branch creation
  - At any time (no schedule defined)
- Automerge
  - At any time (no schedule defined)

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/stargrid-systems/cellguard).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0NC4xMS40IiwidXBkYXRlZEluVmVyIjoiNDQuNDYuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Simon Berger <simon@siku2.io>